(()=>{
  let alarmTimer=null, audioCtx=null, acknowledgedKey='', signupRequests=[], marketConfig=null;
  const WADMIN=U+'/functions/v1/withdrawal-admin-api';
  const SADMIN=U+'/functions/v1/signup-admin-api';
  const MADMIN=U+'/functions/v1/market-data-admin';
  const requestKey=(d)=>{
    const deps=(d?.deposits||[]).filter(x=>['pending','confirm_requested'].includes(x.status)).map(x=>`D${x.id}:${x.status}`).sort();
    const wds=(d?.withdrawals||[]).filter(x=>x.status==='pending').map(x=>`W${x.id}`).sort();
    const sus=(signupRequests||[]).map(x=>`S${x.id}`).sort();
    return [...sus,...deps,...wds].join('|');
  };
  const counts=(d)=>({signup:(signupRequests||[]).length,dep:(d?.deposits||[]).filter(x=>['pending','confirm_requested'].includes(x.status)).length,wd:(d?.withdrawals||[]).filter(x=>x.status==='pending').length});
  function ensureAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}catch{}}
  function beep(){try{ensureAudio();if(!audioCtx)return;const now=audioCtx.currentTime;[0,.22,.44].forEach((off,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.value=i%2?880:660;g.gain.setValueAtTime(.0001,now+off);g.gain.exponentialRampToValueAtTime(.13,now+off+.01);g.gain.exponentialRampToValueAtTime(.0001,now+off+.15);o.connect(g).connect(audioCtx.destination);o.start(now+off);o.stop(now+off+.17);});}catch{}}
  function stopAlarm(){if(alarmTimer){clearInterval(alarmTimer);alarmTimer=null;}}
  function startAlarm(){if(alarmTimer)return;beep();alarmTimer=setInterval(beep,2800);}
  function banner(){let el=document.getElementById('requestAlarmBanner');if(el)return el;el=document.createElement('div');el.id='requestAlarmBanner';el.style.cssText='position:fixed;top:48px;right:18px;z-index:9999;background:#fff4f2;border:1px solid #e14f43;box-shadow:0 4px 16px rgba(0,0,0,.18);padding:11px 13px;min-width:340px;font:12px Arial,Malgun Gothic,sans-serif;display:none';el.innerHTML='<b style="color:#c8352e">처리 대기 요청이 있습니다.</b><div id="requestAlarmText" style="margin-top:5px;color:#444"></div><button id="requestAlarmAck" style="margin-top:8px;height:28px;border:0;background:#e14f43;color:#fff;padding:0 12px;cursor:pointer">알림 확인</button>';document.body.appendChild(el);el.querySelector('#requestAlarmAck').onclick=()=>{acknowledgedKey=requestKey(data);stopAlarm();el.style.display='none';};return el;}
  function badgeFor(btn,n){if(!btn)return;let s=btn.querySelector('.live-badge');if(!s){s=document.createElement('span');s.className='live-badge';s.style.cssText='float:right;background:#e14f43;color:#fff;min-width:18px;height:18px;line-height:18px;text-align:center;border-radius:9px;font-size:10px;margin-top:10px';btn.appendChild(s);}s.textContent=n;s.style.display=n?'inline-block':'none';}
  function updateBadges(d){const c=counts(d);badgeFor(document.querySelector('.nav[data-page="signupApprovals"]'),c.signup);badgeFor(document.querySelector('.nav[data-page="deposits"]'),c.dep);badgeFor(document.querySelector('.nav[data-page="withdrawals"]'),c.wd);}
  function handleAlarm(d){const key=requestKey(d),c=counts(d),el=banner();updateBadges(d);if(key&&key!==acknowledgedKey){el.style.display='block';el.querySelector('#requestAlarmText').textContent=`가입 ${c.signup}건 / 충전 ${c.dep}건 / 출금 ${c.wd}건 처리 대기`;startAlarm();}else if(!key){stopAlarm();el.style.display='none';acknowledgedKey='';}}
  async function apiPost(url,payload){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',apikey:K,Authorization:'Bearer '+token},body:JSON.stringify(payload)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'request_failed');return j;}
  async function signupPost(payload){return apiPost(SADMIN,payload)}
  async function marketPost(payload){return apiPost(MADMIN,payload)}
  function ensureExtraMenus(){ensureSignupMenu();if(!document.querySelector('.nav[data-page="marketData"]')){const pw=document.querySelector('.nav[data-page="password"]');if(pw){const b=document.createElement('button');b.className='nav';b.dataset.page='marketData';b.textContent='시세 API 설정';pw.parentNode.insertBefore(b,pw);b.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');page='marketData';crumbName.textContent='시세 API 설정';await renderMarketData();};}}}
  function ensureSignupMenu(){if(document.querySelector('.nav[data-page="signupApprovals"]'))return;const members=document.querySelector('.nav[data-page="members"]');if(!members)return;const b=document.createElement('button');b.className='nav';b.dataset.page='signupApprovals';b.textContent='가입승인';members.parentNode.insertBefore(b,members);b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');page='signupApprovals';crumbName.textContent='가입승인';renderSignupApprovals();};}
  function renderSignupApprovals(){const c=document.getElementById('content');if(!c)return;const rows=(signupRequests||[]).map(x=>`<tr><td>${esc(x.login_id)}</td><td>${esc(x.display_name||'-')}</td><td>${esc(x.phone||'-')}</td><td>${esc(x.email||'-')}</td><td>${esc(x.birth_date||'-')}</td><td>${esc(x.bank_name||'-')}</td><td>${esc(x.bank_account||'-')}</td><td>${esc(x.account_holder||'-')}</td><td>${esc(x.signup_code||'-')}</td><td>${d(x.approval_requested_at||x.created_at)}</td><td><div class="actions"><button class="btn small green" onclick="approveSignup('${x.id}')">승인</button><button class="btn small red" onclick="rejectSignup('${x.id}')">반려</button></div></td></tr>`).join('');c.innerHTML=title('가입승인')+`<div class="warn">가입코드 검증을 통과한 신규 가입 요청입니다. 승인 전에는 로그인할 수 없습니다.</div><div class="table-wrap"><table class="grid"><thead><tr><th>아이디</th><th>예금주명</th><th>핸드폰</th><th>이메일</th><th>생년월일</th><th>은행</th><th>계좌번호</th><th>예금주</th><th>가입코드</th><th>신청일시</th><th>처리</th></tr></thead><tbody>${rows||'<tr><td colspan="11"><div class="empty">가입 승인 대기 요청이 없습니다.</div></td></tr>'}</tbody></table></div>`;}
  async function renderMarketData(){const c=document.getElementById('content');if(!c)return;c.innerHTML=title('시세 API 설정')+'<div class="empty">설정을 불러오는 중입니다.</div>';try{marketConfig=await marketPost({action:'get_config'});c.innerHTML=title('시세 API 설정')+`<div class="card" style="max-width:720px"><h3>실시간 시세 공급사</h3><div class="form" style="grid-template-columns:180px 1fr"><label>공급사</label><input value="iTick" readonly><label>API 주소</label><input id="marketApiBase" value="${esc(marketConfig.api_base||'https://api-free.itick.org/future')}"><label>현재 API Key</label><input value="${esc(marketConfig.token_masked||'미설정')}" readonly><label>새 API Key</label><input id="marketApiToken" type="password" placeholder="변경할 때만 입력"></div><div class="hint">회원용 HTS에는 API Key가 노출되지 않습니다. 모든 시세 요청은 VELTRO 서버를 통해 전달됩니다.</div><div class="form-actions"><button class="btn" onclick="saveMarketDataConfig()">저장</button><button class="btn green" onclick="testMarketDataConfig()">NQ 연결 테스트</button><button class="btn gray" onclick="clearMarketDataConfig()">API Key 삭제</button><span id="marketAdminState" style="padding:7px 0;color:${marketConfig.configured?'#20804f':'#b8352f'}">${marketConfig.configured?'설정됨':'미설정'}</span></div></div>`;}catch(e){c.innerHTML=title('시세 API 설정')+`<div class="warn">${esc(e.message)}</div>`;}}
  window.saveMarketDataConfig=async()=>{const tokenValue=String(document.getElementById('marketApiToken')?.value||'').trim(),apiBase=String(document.getElementById('marketApiBase')?.value||'').trim();try{await marketPost({action:'save_config',token:tokenValue,api_base:apiBase});alert('시세 API 설정이 저장되었습니다.');await renderMarketData()}catch(e){alert(e.message)}};
  window.testMarketDataConfig=async()=>{const el=document.getElementById('marketAdminState');if(el)el.textContent='연결 확인 중...';try{const r=await marketPost({action:'test',region:'US',code:'NQ'});if(el){el.style.color='#20804f';el.textContent=`연결됨 · NQ ${r.quote?.ld??'-'}`}}catch(e){if(el){el.style.color='#b8352f';el.textContent='연결 실패 · '+e.message}}};
  window.clearMarketDataConfig=async()=>{if(!confirm('저장된 시세 API Key를 삭제할까요?'))return;try{await marketPost({action:'save_config',clear:true,api_base:document.getElementById('marketApiBase')?.value||''});await renderMarketData()}catch(e){alert(e.message)}};
  window.approveSignup=async id=>{if(!confirm('이 회원의 가입을 승인할까요?'))return;try{await signupPost({action:'approve',user_id:id});alert('가입 승인이 완료되었습니다. 이제 회원이 로그인할 수 있습니다.');await refreshLive();if(page==='signupApprovals')renderSignupApprovals()}catch(e){alert(e.message)}};
  window.rejectSignup=async id=>{const note=prompt('반려 사유를 입력하세요.','')||'';if(!confirm('가입 요청을 반려할까요?'))return;try{await signupPost({action:'reject',user_id:id,note});alert('가입 요청이 반려되었습니다.');await refreshLive();if(page==='signupApprovals')renderSignupApprovals()}catch(e){alert(e.message)}};
  async function refreshLive(){try{if(!token)return;ensureExtraMenus();const [next,sr]=await Promise.all([post(ADMIN,{action:'dashboard'},true),signupPost({action:'list'})]);data=next;signupRequests=sr.requests||[];handleAlarm(next);const active=document.activeElement;const editing=active&&['INPUT','TEXTAREA','SELECT'].includes(active.tagName);const modalOpen=document.querySelector('.modal-mask');if(page==='signupApprovals'&&!editing&&!modalOpen)renderSignupApprovals();else if(page==='marketData'){/* 설정 입력 보호 */}else if(!editing&&!modalOpen&&['deposits','withdrawals','money','performance'].includes(page))render();}catch(e){console.warn('admin live refresh failed',e);}}
  async function wact(action,id,note=''){const r=await fetch(WADMIN,{method:'POST',headers:{'content-type':'application/json',apikey:K,Authorization:'Bearer '+token},body:JSON.stringify({action,id,admin_note:note})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'request_failed');await load();return j;}
  window.approveWithdrawal=async id=>{if(!confirm('출금 승인을 처리할까요?'))return;try{await wact('approve',id);alert('출금 승인이 완료되었습니다.')}catch(e){alert(e.message)}};
  window.rejectWithdrawal=async id=>{const note=prompt('반려사유를 입력하세요.')||'';try{await wact('reject',id,note);alert('출금이 반려되었으며 예약된 금액은 잔고로 반환되었습니다.')}catch(e){alert(e.message)}};
  document.addEventListener('pointerdown',ensureAudio,{once:true,capture:true});
  const boot=setInterval(()=>{if(token){clearInterval(boot);ensureExtraMenus();refreshLive();setInterval(refreshLive,5000);}},500);
})();
