(()=>{
  let alarmTimer=null, audioCtx=null, acknowledgedKey='', signupRequests=[];
  const WADMIN=U+'/functions/v1/withdrawal-admin-api';
  const SADMIN=U+'/functions/v1/signup-admin-api';
  const requestKey=(d)=>{
    const deps=(d?.deposits||[]).filter(x=>['pending','confirm_requested'].includes(x.status)).map(x=>`D${x.id}:${x.status}`).sort();
    const wds=(d?.withdrawals||[]).filter(x=>x.status==='pending').map(x=>`W${x.id}`).sort();
    const sus=(signupRequests||[]).map(x=>`S${x.id}`).sort();
    return [...sus,...deps,...wds].join('|');
  };
  const counts=(d)=>({signup:(signupRequests||[]).length,dep:(d?.deposits||[]).filter(x=>['pending','confirm_requested'].includes(x.status)).length,wd:(d?.withdrawals||[]).filter(x=>x.status==='pending').length});
  function ensureAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}catch{}}
  function beep(){try{ensureAudio();if(!audioCtx)return;const now=audioCtx.currentTime;[0,.22,.44].forEach((off,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.value=i%2?880:660;g.gain.setValueAtTime(.0001,now+off);g.gain.exponentialRampToValueAtTime(.13,now+off+.01);g.gain.exponentialRampToValueAtTime(.0001,now+off+.15);o.connect(g).connect(audioCtx.destination);o.start(now+off);o.stop(now+off+.17);});}catch{}}
  function stopAlarm(){if(alarmTimer){clearInterval(alarmTimer);alarmTimer=null;}}
  function startAlarm(){if(alarmTimer)return;beep();alarmTimer=setInterval(beep,2800);}
  function banner(){let el=document.getElementById('requestAlarmBanner');if(el)return el;el=document.createElement('div');el.id='requestAlarmBanner';el.style.cssText='position:fixed;top:48px;right:18px;z-index:9999;background:#fff4f2;border:1px solid #e14f43;box-shadow:0 4px 16px rgba(0,0,0,.18);padding:11px 13px;min-width:340px;font:12px Arial,Malgun Gothic,sans-serif;display:none';el.innerHTML='<b style="color:#c8352e">처리 대기 요청이 있습니다.</b><div id="requestAlarmText" style="margin-top:5px;color:#444"></div><button id="requestAlarmAck" style="margin-top:8px;height:28px;border:0;background:#e14f43;color:#fff;padding:0 12px;cursor:pointer">알림 확인</button>';document.body.appendChild(el);el.querySelector('#requestAlarmAck').onclick=()=>{acknowledgedKey=requestKey(data);stopAlarm();el.style.display='none';};return el;}
  function badgeFor(btn,n){if(!btn)return;let s=btn.querySelector('.live-badge');if(!s){s=document.createElement('span');s.className='live-badge';s.style.cssText='float:right;background:#e14f43;color:#fff;min-width:18px;height:18px;line-height:18px;text-align:center;border-radius:9px;font-size:10px;margin-top:10px';btn.appendChild(s);}s.textContent=n;s.style.display=n?'inline-block':'none';}
  function updateBadges(d){const c=counts(d);badgeFor(document.querySelector('.nav[data-page="signupApprovals"]'),c.signup);badgeFor(document.querySelector('.nav[data-page="deposits"]'),c.dep);badgeFor(document.querySelector('.nav[data-page="withdrawals"]'),c.wd);}
  function handleAlarm(d){const key=requestKey(d),c=counts(d),el=banner();updateBadges(d);if(key&&key!==acknowledgedKey){el.style.display='block';el.querySelector('#requestAlarmText').textContent=`가입 ${c.signup}건 / 충전 ${c.dep}건 / 출금 ${c.wd}건 처리 대기`;startAlarm();}else if(!key){stopAlarm();el.style.display='none';acknowledgedKey='';}}
  async function signupPost(payload){const r=await fetch(SADMIN,{method:'POST',headers:{'content-type':'application/json',apikey:K,Authorization:'Bearer '+token},body:JSON.stringify(payload)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'request_failed');return j;}
  function ensureSignupMenu(){if(document.querySelector('.nav[data-page="signupApprovals"]'))return;const members=document.querySelector('.nav[data-page="members"]');if(!members)return;const b=document.createElement('button');b.className='nav';b.dataset.page='signupApprovals';b.textContent='가입승인';members.parentNode.insertBefore(b,members);b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');page='signupApprovals';crumbName.textContent='가입승인';renderSignupApprovals();};}
  function renderSignupApprovals(){const c=document.getElementById('content');if(!c)return;const rows=(signupRequests||[]).map(x=>`<tr><td>${esc(x.login_id)}</td><td>${esc(x.display_name||'-')}</td><td>${esc(x.phone||'-')}</td><td>${esc(x.email||'-')}</td><td>${esc(x.birth_date||'-')}</td><td>${esc(x.bank_name||'-')}</td><td>${esc(x.bank_account||'-')}</td><td>${esc(x.account_holder||'-')}</td><td>${esc(x.signup_code||'-')}</td><td>${d(x.approval_requested_at||x.created_at)}</td><td><div class="actions"><button class="btn small green" onclick="approveSignup('${x.id}')">승인</button><button class="btn small red" onclick="rejectSignup('${x.id}')">반려</button></div></td></tr>`).join('');c.innerHTML=title('가입승인')+`<div class="warn">가입코드 검증을 통과한 신규 가입 요청입니다. 승인 전에는 로그인할 수 없습니다.</div><div class="table-wrap"><table class="grid"><thead><tr><th>아이디</th><th>예금주명</th><th>핸드폰</th><th>이메일</th><th>생년월일</th><th>은행</th><th>계좌번호</th><th>예금주</th><th>가입코드</th><th>신청일시</th><th>처리</th></tr></thead><tbody>${rows||'<tr><td colspan="11"><div class="empty">가입 승인 대기 요청이 없습니다.</div></td></tr>'}</tbody></table></div>`;}
  window.approveSignup=async id=>{if(!confirm('이 회원의 가입을 승인할까요?'))return;try{await signupPost({action:'approve',user_id:id});alert('가입 승인이 완료되었습니다. 이제 회원이 로그인할 수 있습니다.');await refreshLive();if(page==='signupApprovals')renderSignupApprovals()}catch(e){alert(e.message)}};
  window.rejectSignup=async id=>{const note=prompt('반려 사유를 입력하세요.','')||'';if(!confirm('가입 요청을 반려할까요?'))return;try{await signupPost({action:'reject',user_id:id,note});alert('가입 요청이 반려되었습니다.');await refreshLive();if(page==='signupApprovals')renderSignupApprovals()}catch(e){alert(e.message)}};
  async function refreshLive(){try{if(!token)return;ensureSignupMenu();const [next,sr]=await Promise.all([post(ADMIN,{action:'dashboard'},true),signupPost({action:'list'})]);data=next;signupRequests=sr.requests||[];handleAlarm(next);const active=document.activeElement;const editing=active&&['INPUT','TEXTAREA','SELECT'].includes(active.tagName);const modalOpen=document.querySelector('.modal-mask');if(page==='signupApprovals'&&!editing&&!modalOpen)renderSignupApprovals();else if(!editing&&!modalOpen&&['deposits','withdrawals','money','performance'].includes(page))render();}catch(e){console.warn('admin live refresh failed',e);}}
  async function wact(action,id,note=''){const r=await fetch(WADMIN,{method:'POST',headers:{'content-type':'application/json',apikey:K,Authorization:'Bearer '+token},body:JSON.stringify({action,id,admin_note:note})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'request_failed');await load();return j;}
  window.approveWithdrawal=async id=>{if(!confirm('출금 승인을 처리할까요?'))return;try{await wact('approve',id);alert('출금 승인이 완료되었습니다.')}catch(e){alert(e.message)}};
  window.rejectWithdrawal=async id=>{const note=prompt('반려사유를 입력하세요.')||'';try{await wact('reject',id,note);alert('출금이 반려되었으며 예약된 금액은 잔고로 반환되었습니다.')}catch(e){alert(e.message)}};
  document.addEventListener('pointerdown',ensureAudio,{once:true,capture:true});
  const boot=setInterval(()=>{if(token){clearInterval(boot);ensureSignupMenu();refreshLive();setInterval(refreshLive,5000);}},500);
})();
